### ISSUE TITLE
Error while uninstalling Homebrew

### ISSUE THREAD

**Issue by CodeBitesU** [Homebrew/install#646] opened 2022-04-27 12:25 UTC
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x ] your problem was from running the official `install` or `uninstall` script?
- [x ] after installation: ran `brew config` and `brew doctor` and included their output with your issue? If you couldn't install: provided your OS version with the output of your issue?

## What you were trying to do (and why)

I was trying to delete Homebrew after I failed opening minetest.

## What happened (include command output)

I couldn't delete Homebrew because this came:

curl: (22) The requested URL returned error: 404

<details>
  <summary>Command output</summary>
  <pre>

 Here is the Full code:
MacBook-Air:~ User$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
curl: (22) The requested URL returned error: 404
MacBook-Air:~ User$ 

  </pre>
</details>

## What you expected to happen
I expected it to delete
## Step-by-step reproduction instructions (by running `brew` commands)

 Here is the Full code:
MacBook-Air:~ User$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
curl: (22) The requested URL returned error: 404
MacBook-Air:~ User$

**Comment by Bo98** [comment] 2022-04-27 12:31
Duplicate of #645. Swap `HEAD` with `master` if you need a workaround.

**Closed by Bo98** 2022-04-27 12:31 UTC

**Comment by CodeBitesU** [comment] 2022-04-27 12:45
If i do this: 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

it responds:

curl: (22) The requested URL returned error: 404
Failed to fetch Homebrew .gitignore!

**Comment by Bo98** [comment] 2022-04-27 12:50
Argh sorry, looks like there's some `HEAD` references inside scripts too. If it's urgent: download the file, edit it and run it.

We're speaking with GitHub to get to the bottom of the issue.

**Comment by Bo98** [comment] 2022-04-27 16:45
GitHub have rolled out a fix. Everything should be working now.

**Comment by CodeBitesU** [comment] 2022-04-27 19:03
It is semi-urgent but I'm very thankful for any help.
