### ISSUE TITLE
https://brew.sh/index_pl - 404

### ISSUE THREAD

**Issue by bryn1u** [Homebrew/install#647] opened 2022-04-27 13:15 UTC
On the Site:
https://brew.sh/index_pl

The link doesn't work anymore :( Im getting 404. Probably url has changed.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

**Comment by Bo98** [comment] 2022-04-27 13:16
Duplicate of #645

**Closed by Bo98** 2022-04-27 13:16 UTC
