### ISSUE TITLE
Headless Xcode Command Line Tools installation failed on 10.14

### ISSUE THREAD

**Issue by Nezz** [Homebrew/install#206] opened 2019-06-04 14:58 UTC
We have an automated Jenkins job that sets up machines by installing Homebrew on them. It started failing recently.

Reproduction:
1. Have a fresh installation of macOS Mojave (tested with 10.14.4)
2. Run `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Expected outcome:
Homebrew installs successfully in interactive shell and non-interactive shell

Actual outcome:
_In interactive shell_
<img width="709" alt="Screenshot 2019-06-04 at 17 50 40" src="https://user-images.githubusercontent.com/431167/58889366-7635fa00-86f1-11e9-90bb-eb86a6d42f8c.png">

_In non-interactive shell_
```
[2019-06-04T14:42:20.932Z] Installing homebrew
[2019-06-04T14:42:21.189Z] ==> This script will install:
[2019-06-04T14:42:21.189Z] /usr/local/bin/brew
[2019-06-04T14:42:21.189Z] /usr/local/share/doc/homebrew
[2019-06-04T14:42:21.189Z] /usr/local/share/man/man1/brew.1
[2019-06-04T14:42:21.189Z] /usr/local/share/zsh/site-functions/_brew
[2019-06-04T14:42:21.189Z] /usr/local/etc/bash_completion.d/brew
[2019-06-04T14:42:21.189Z] /usr/local/Homebrew
[2019-06-04T14:42:21.189Z] ==> The following existing directories will be made group writable:
[2019-06-04T14:42:21.189Z] /usr/local/lib
[2019-06-04T14:42:21.189Z] /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> The following existing directories will have their owner set to anka:
[2019-06-04T14:42:21.189Z] /usr/local/lib
[2019-06-04T14:42:21.189Z] /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> The following existing directories will have their group set to admin:
[2019-06-04T14:42:21.189Z] /usr/local/lib
[2019-06-04T14:42:21.189Z] /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> The following new directories will be created:
[2019-06-04T14:42:21.189Z] /usr/local/bin
[2019-06-04T14:42:21.189Z] /usr/local/etc
[2019-06-04T14:42:21.189Z] /usr/local/include
[2019-06-04T14:42:21.189Z] /usr/local/sbin
[2019-06-04T14:42:21.189Z] /usr/local/share
[2019-06-04T14:42:21.189Z] /usr/local/var
[2019-06-04T14:42:21.189Z] /usr/local/opt
[2019-06-04T14:42:21.189Z] /usr/local/share/zsh
[2019-06-04T14:42:21.189Z] /usr/local/share/zsh/site-functions
[2019-06-04T14:42:21.189Z] /usr/local/var/homebrew
[2019-06-04T14:42:21.189Z] /usr/local/var/homebrew/linked
[2019-06-04T14:42:21.189Z] /usr/local/Cellar
[2019-06-04T14:42:21.189Z] /usr/local/Caskroom
[2019-06-04T14:42:21.189Z] /usr/local/Homebrew
[2019-06-04T14:42:21.189Z] /usr/local/Frameworks
[2019-06-04T14:42:21.189Z] ==> The Xcode Command Line Tools will be installed.
[2019-06-04T14:42:21.189Z] ==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.189Z] ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/lib /usr/local/lib/pkgconfig
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.445Z] ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /bin/mkdir -p /Users/anka/Library/Caches/Homebrew
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /bin/chmod g+rwx /Users/anka/Library/Caches/Homebrew
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /usr/sbin/chown anka /Users/anka/Library/Caches/Homebrew
[2019-06-04T14:42:21.701Z] ==> Searching online for the Command Line Tools
[2019-06-04T14:42:21.701Z] ==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
[2019-06-04T14:42:43.596Z] ==> Downloading and installing Homebrew...
[2019-06-04T14:42:43.596Z] xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
[2019-06-04T14:42:43.596Z] Failed during: git init -q
script returned exit code 1
```
Also, the following popup is visible on the machine:
<img width="374" alt="Screenshot 2019-06-04 at 17 44 55" src="https://user-images.githubusercontent.com/431167/58890822-0d9c4c80-86f4-11e9-8fdf-7346462cad47.png">

Here is the non-interactive output from the 8th of May when it was still working correctly:
```
20:31:15  Installing homebrew
20:31:16  ==> This script will install:
20:31:16  /usr/local/bin/brew
20:31:16  /usr/local/share/doc/homebrew
20:31:16  /usr/local/share/man/man1/brew.1
20:31:16  /usr/local/share/zsh/site-functions/_brew
20:31:16  /usr/local/etc/bash_completion.d/brew
20:31:16  /usr/local/Homebrew
20:31:16  ==> The following existing directories will be made group writable:
20:31:16  /usr/local/lib
20:31:16  /usr/local/lib/pkgconfig
20:31:16  ==> The following existing directories will have their owner set to anka:
20:31:16  /usr/local/lib
20:31:16  /usr/local/lib/pkgconfig
20:31:16  ==> The following existing directories will have their group set to admin:
20:31:16  /usr/local/lib
20:31:16  /usr/local/lib/pkgconfig
20:31:16  ==> The following new directories will be created:
20:31:16  /usr/local/bin
20:31:16  /usr/local/etc
20:31:16  /usr/local/include
20:31:16  /usr/local/sbin
20:31:16  /usr/local/share
20:31:16  /usr/local/var
20:31:16  /usr/local/opt
20:31:16  /usr/local/share/zsh
20:31:16  /usr/local/share/zsh/site-functions
20:31:16  /usr/local/var/homebrew
20:31:16  /usr/local/var/homebrew/linked
20:31:16  /usr/local/Cellar
20:31:16  /usr/local/Caskroom
20:31:16  /usr/local/Homebrew
20:31:16  /usr/local/Frameworks
20:31:16  ==> The Xcode Command Line Tools will be installed.
20:31:16  ==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/lib /usr/local/lib/pkgconfig
20:31:16  ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/lib /usr/local/lib/pkgconfig
20:31:17  ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/lib /usr/local/lib/pkgconfig
20:31:17  ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/lib /usr/local/lib/pkgconfig
20:31:17  ==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
20:31:17  ==> /usr/bin/sudo /usr/sbin/chown anka /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/include /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
20:31:17  ==> /usr/bin/sudo /bin/mkdir -p /Users/anka/Library/Caches/Homebrew
20:31:17  ==> /usr/bin/sudo /bin/chmod g+rwx /Users/anka/Library/Caches/Homebrew
20:31:17  ==> /usr/bin/sudo /usr/sbin/chown anka /Users/anka/Library/Caches/Homebrew
20:31:17  ==> Searching online for the Command Line Tools
20:31:17  ==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
20:31:33  ==> Installing Command Line Tools (macOS Mojave version 10.14) for Xcode-10.2
20:31:33  ==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ (macOS\ Mojave\ version\ 10.14)\ for\ Xcode-10.2
20:31:33  Software Update Tool
20:31:33  
20:31:33  
20:31:37  Downloading Command Line Tools (macOS Mojave version 10.14) for Xcode
20:31:37  Downloaded Command Line Tools (macOS Mojave version 10.14) for Xcode
20:32:34  Installing Command Line Tools (macOS Mojave version 10.14) for Xcode
20:32:34  Done with Command Line Tools (macOS Mojave version 10.14) for Xcode
20:32:34  Done.
20:32:34  ==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
20:32:34  ==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
20:32:34  ==> Downloading and installing Homebrew...
20:32:41  From https://github.com/Homebrew/brew
20:32:41   * [new branch]      master     -> origin/master
[...]
20:32:41   * [new tag]         2.1.2      -> 2.1.2
20:32:41  HEAD is now at 37f4b9264 Merge pull request #6108 from Homebrew/dependabot/bundler/docs/unicode-display_width-1.6.0
20:32:46  ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
20:32:46    https://github.com/Homebrew/brew#donations
20:32:49  ==> Tapping homebrew/core
20:32:49  Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
20:32:56  Checking out files:  78% (3945/5007)   
[...]
Checking out files: 100% (5007/5007), done.
20:33:11  Tapped 2 commands and 4775 formulae (5,032 files, 12.4MB).
20:33:12  Already up-to-date.
20:33:12  ==> Installation successful!
```

**Comment by Nezz** [comment] 2019-06-04 15:22
It seems that Apple is recommending Xcode 11.0 beta CLI tools to be installed instead of the stable version. This seems to throw off the Command Line Tools installation logic:
```
/usr/sbin/softwareupdate -l
Software Update Tool

Finding available software
Software Update found the following new or updated software:
   * macOS 10.14.5 Update- 
	macOS 10.14.5 Update ( ), 2420848K [recommended] [restart]
   * iTunes Device Support Update- 
	iTunes Device Support Update ( ), 105795K [recommended] [restart]
   * Command Line Tools beta 1 for Xcode-11.0
	Command Line Tools beta 1 for Xcode (11.0), 243172K [recommended]
```

**Comment by MikeMcQuaid** [comment] 2019-06-04 15:52
We'll accept a pull request to fix this. You may want to investigate another way to install Xcode/the CLT on those machines rather than using our installer

**Comment by Nezz** [comment] 2019-06-04 15:54
Why are you closing this if it's not fixed? I think it'd be nice to keep it open as long as Apple doesn't fix their software update to avoid duplicate reports.

**Comment by MikeMcQuaid** [comment] 2019-06-04 15:56
> Why are you closing this if it's not fixed?

This is not a bug that affects everyone and it's unclear that it's not entirely specific to your setup. We don't believe in having issues open that are not directly actionable.

**Comment by Nezz** [comment] 2019-06-04 16:09
I'm afraid it affects everyone who don't have Command Line Tools installed. I guess this will mainly break automated CI setups. Looks like it's best to just wait for Apple to fix the list of software updates though.

**Comment by MikeMcQuaid** [comment] 2019-06-04 16:20
> I'm afraid it affects everyone who don't have Command Line Tools installed.

We will see more issue if that's the case.

**Comment by aledeganopix4d** [comment] 2019-06-05 11:43
Hello we have exactly the same issue. Also in a display-less environment. Also on Mojave 10.14.4.

**Comment by MikeMcQuaid** [comment] 2019-06-05 11:58
We will accept a PR to resolve this issue.

**Comment by NorseGaud** [comment] 2019-06-05 23:25
I've opened https://apple.stackexchange.com/questions/361727/how-do-i-install-beta-command-line-tools-using-softwareupdate-l-on-10-14-5 to figure out why softwareupdate won't list it. I'll do a PR once I find the solution.

**Comment by NorseGaud** [comment] 2019-06-05 23:36
Ok, the beta version of CLT was a bug and that likely isn't the issue: https://apple.stackexchange.com/questions/361609/command-line-tools-beta-1-for-xcode-11-0-offered-as-an-update-in-the-current-lat

**Comment by marco-m** [comment] 2019-06-06 07:47
@NorseGaud thanks for following up.

As pointed out by @Nezz above, this is breaking any CI system that is using brew to bring in the toolchain.

**Comment by MikeMcQuaid** [comment] 2019-06-06 07:49
> As pointed out by @Nezz above, this is breaking any CI system that is using brew to bring in the toolchain.

Incorrect, it is not breaking Homebrew's CI system: https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=11365

**Comment by Nezz** [comment] 2019-06-06 08:29
@MikeMcQuaid Does the azure agent have CLT or Xcode pre-installed?

**Comment by aledeganopix4d** [comment] 2019-06-06 08:31
> Incorrect, it is not breaking Homebrew's CI system: https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=11365

I'm not familiar with Azure pipelines, but the test you linked would seem to be executed on "High Sierra".
Am I reading it right?

**Comment by Nezz** [comment] 2019-06-06 08:36
That's a good point @aledeganopix4d. The image has a wide variety of Xcode versions pre-installed:
https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.13-Readme.md

**Comment by Nezz** [comment] 2019-06-06 08:51
That's a good point @aledeganopix4d.
```
Installing Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1
```

@MikeMcQuaid Can you try re-running it on 10.14?

**Comment by MikeMcQuaid** [comment] 2019-06-06 09:19
I'm testing it in https://github.com/Homebrew/install/pull/208. Regardless if it fails: the only fix we can do is tell the user to manually run `xcode-select --install`. There is no Apple officially supported way to install the command-line tools non-interactively. There is nothing Homebrew can do about that. If you are relying on Homebrew to do that for you through our installer: bad luck.

**Comment by NorseGaud** [comment] 2019-06-06 11:26
> @NorseGaud thanks for following up.
> 
> As pointed out by @Nezz above, this is breaking any CI system that is using brew to bring in the toolchain.

Hey @marco-m, yep, I automate building out tags/layers with specific things on them for our Anka CI/CD so we can pull one of those layers to build a project layer on top. Brew is one of those layers and installation using the installer fails when using 10.14.5.

**Comment by NorseGaud** [comment] 2019-06-06 11:29
> I'm testing it in #208. Regardless if it fails: the only fix we can do is tell the user to manually run `xcode-select --install`. There is no Apple officially supported way to install the command-line tools non-interactively. There is nothing Homebrew can do about that. If you are relying on Homebrew to do that for you through our installer: bad luck.

That's fine; I'm going to find a solution and add support for it to the installer as you suggested in a PR. 

Since this issue is for tracking and notifying people that support is being worked towards, how do you feel about re-opening this issue so that other issues aren't opened for the same thing?

**Comment by Nezz** [comment] 2019-06-06 11:33
FYI: I worked around it by installing CLT manually on a VM base image. I had to download it from [Apple's download site](https://developer.apple.com/download/more/) because the GUI install in the OS is broken too.

**Comment by NorseGaud** [comment] 2019-06-06 11:44
Opened developer support case 100827740080 with apple for this. Waiting to hear back.

**Comment by NorseGaud** [comment] 2019-06-07 21:44
Submitted a bug report (Jun 7, 2019 at 5:21 PM – FB6132845) since the folks in developer support seem like bots and are extremely unhelpful.

**Comment by MikeMcQuaid** [comment] 2019-06-10 17:48
Fixed by Apple now.

**Closed by MikeMcQuaid** 2019-06-10 17:48 UTC

**Comment by NorseGaud** [comment] 2019-06-10 20:42
Party --  thanks Mike!
